### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-svfq0#3]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by khallslearn** [comment]
![Placeholder](https://user-images.githubusercontent.com/75588413/196745697-d98ecc03-dc00-4b61-94f7-12734059aa9b.png)
